version: "3.8"

services:
  ecommerce:
    build: .
    restart: always
    container_name: docker_node_mongo
    environment:
      - JWT_SECRET=secret
      - COOKIE_P=felixing
      - SMTP_USERNAME=foogundipe@student.oauife.edu.ng
      - SMTP_PASSWORD=@felix2000
      - PUBLIC_KEY=FLWPUBK_TEST-28920e8d073b8aed1f16631b7f7f1c24-X
      - SECRET_KEY=FLWSECK_TEST-5332983ca51e9ff3c895afb81f2a99c3-X
      - MONGO_URL="mongodb+srv://leksyking:leksyking7@e-com.tyzqk.mongodb.net/?retryWrites=true&w=majority"
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    build: db
    ports:
      - "27017:27017"
