version: "3.8"

services:
  ecommerce:
    build: .
    restart: always
    container_name: docker_node_mongo
    environment:
      - JWT_SECRET=secret
      - COOKIE_P=felixing
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - PUBLIC_KEY=
      - SECRET_KEY=
      - MONGO_URL=
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    build: db
    ports:
      - "27017:27017"
